### ISSUE TITLE
Add support for Xfce

### ISSUE THREAD

**Issue by m8t** [thesamet/webilder#1]
I'm attaching a patch to add a radio button under GNOME and KDE in the Advanced tab of the Preferences dialog. It will in turn make use of the xfconf-query command.

**Comment by m8t** [comment]
Since I don't know how to attach a patch, you can pick it up here: 

http://foo-projects.org/pipermail/xfce/attachments/20100624/7e4d7621/attachment-0001.bin

**Comment by thesamet** [comment]
Thank you for implementing this. I know that some users have been asking for this feature for a while. The patch looks good. I'll commit it later today.

I am new to github, but I think that the git5 way of sending patches is to fork the project, apply the changes in the forked project, and then submit a pull request to me: http://help.github.com/forking/

Thanks again,
Nadav

**Comment by thesamet** [comment]
Done!

**Comment by m8t** [comment]
That's what I thought too, thanks for the info, and thanks for applying the patch :)
