### ISSUE TITLE
Photos do not rotate on Gnome

### ISSUE THREAD

**Issue by debianuser2010** [thesamet/webilder#15]
Debian Squeeze 6.0, Gnome 2.30.2 webilder can manually set WBZ for desktop but does not automatically rotate wallpaper every 5 minutes as set in preferences. Advice?  Thanks!

**Comment by thesamet** [comment]
Do you have the applet running inside the gnome panel (upper panel on the screen)?

**Comment by debianuser2010** [comment]
Yes, I do.  The Webilder panel icon is present on the launcher

**Comment by thesamet** [comment]
Does changing the wallpaper work from Webilder Desktop?

**Comment by debianuser2010** [comment]
Yes, I can change it manually from within webilder

**Comment by thesamet** [comment]
From the command line,  type

WebilderApplet run-in-window

It is supposed to create a tiny window with the webilder applet running on it. Let it run for 5 minutes to see what it's going. We might get some helpful debugging text printed on the console.

Also, does right clicking on it, and choosing 'Next photo' cause a rotation?

**Comment by debianuser2010** [comment]
/usr/local/lib/python2.6/dist-packages/webilder/webilder_gnome_applet.py:41: DeprecationWarning: Use the new widget gtk.Tooltip
  self.tooltips = gtk.Tooltips()
/usr/local/lib/python2.6/dist-packages/webilder/webilder_gnome_applet.py:42: DeprecationWarning: Use the new widget gtk.Tooltip
  self.tooltips.enable()
/usr/local/lib/python2.6/dist-packages/webilder/webilder_gnome_applet.py:90: DeprecationWarning: Use the new widget gtk.Tooltip
  self.tooltips.enable()
/usr/local/lib/python2.6/dist-packages/webilder/webilder_gnome_applet.py:91: DeprecationWarning: Use the new widget gtk.Tooltip
  self.tooltips.set_tip(self.applet, text)

(webilder_applet:12519): Bonobo-WARNING **: Never got frame, control died - abnormal exit condition
Rotating...

The desktop app DOES rotate pics automatically; the applet does not.

**Comment by debianuser2010** [comment]
Any advice on this?

**Comment by thesamet** [comment]
I think that at this point we'll have to go into debugging the Python code. If you're comfortable doing that I can provide guidance. Otherwise I'm going to set up more logging in the applet so we might be able to solve it in the next release.

**Comment by debianuser2010** [comment]
I would love to help debug.  Awaiting your instructions :-)
