### ISSUE TITLE
Wrong installation path for bonobo description file on Fedora 64bit

### ISSUE THREAD

**Issue by sgros** [thesamet/webilder#17]
setup.py installs bonobo description file into /usr/lib/bonobo/servers but on 64-bit machines (at least Fedora 14) it should be in /usr/lib64/bonobo/servers.

I did initial package for Fedora and Pavel Zhukov made a simple patch as a temporary workaround:

https://bugzilla.redhat.com/show_bug.cgi?id=684398

**Comment by thesamet** [comment]
I have added a new command line flag to setup.py that will let you choose where you want the bonobo description file installed. In the 64-bit case you should use:
python setup.py --bonobo_path=lib64/bonobo/servers

This has been commited in 620203863e22cf6dc41278691a880d6cc96f3704.
