### ISSUE TITLE
Bug: Error occured while downloading images

### ISSUE THREAD

**Issue by avoura** [thesamet/webilder#18]
When trying to download images from Flickr in Webilder, I get the following:

Error occured while downloading images

<urlopen error [Errno -2] Name or service not known>

This was after having set up various search tags/album names in the Preferences.

**Comment by thesamet** [comment]
If it worked for you before, then it might be a temporary problem with the Flickr API.

If you are behind an http proxy, you have to set up an environment variable so Webilder will use it. You can try:

http_proxy=http://yourproxy:someport webilder_desktop

To set this variable system-wide, add it to /etc/environment

Please let me know if this helps.
