### ISSUE TITLE
Bug?: applet tooltip displays "Version 0.6.9 released"... in v0.7!

### ISSUE THREAD

**Issue by mittfh** [thesamet/webilder#20]
Not sure if this counts as a bug - it's more an annoyance.

The tooltip on the applet always displays the text "Version 0.6.9 released" above the name of the photo currently being displayed on the desktop. I would have thought this functionality was introduced as a subtle reminder that a newer version of Webilder had been released. But when it still displays the reminder for version 0.6.9 in version 0.7, it's a little irritating.

(In case it's relevant [probably not given the nature of this bug], observed in Mandriva 2010.2 / Mageia 1.0)

**Comment by thesamet** [comment]
Thanks for letting me know! Fixed.
