### ISSUE TITLE
webilder 0.7.1 doesn't automatically start after reboot with ubuntu 11.04

### ISSUE THREAD

**Issue by bhupi** [thesamet/webilder#21]
I installed the lastest release of webilder under ubuntu 11.04 using unity.  I did one reboot and webilder started automatically and ran fine.   Today I booted up and webilder didn't start.  I did the following at a terminal window:

/usr/bin/webilder_unity_indicator &
[1] 3337
laptop17:~$ Traceback (most recent call last):
  File "/usr/bin/webilder_unity_indicator", line 9, in <module>
    load_entry_point('Webilder==0.7.1', 'console_scripts', 'webilder_unity_indicator')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 305, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2244, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1954, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/webilder/webilder_unity_indicator.py", line 14, in <module>
    from webilder.base_applet import BaseApplet
  File "/usr/lib/pymodules/python2.7/webilder/base_applet.py", line 11, in <module>
    from webilder.config import config, set_wallpaper, reload_config
  File "/usr/lib/pymodules/python2.7/webilder/config.py", line 126, in <module>
    config = ConfigObject(DEFAULT_CONFIG_FILE)  # pylint: disable=C0103
  File "/usr/lib/pymodules/python2.7/webilder/config.py", line 34, in **init**
    raise ValueError, _("collection.dir is set to a non-directory, "
ValueError: collection.dir is set to a non-directory, check your config file.

I found that if I edit my webilder.conf file, change the collection.dir field, all I did was I removed the quotes and saved the file,  then try to run webilder again it still fails.  I then put the collection.dir field back to how I originally had it and start webilder and it works.  So I am able to get it working but I have to manually do some tweaking.

**Comment by thesamet** [comment]
Can you file a new issue for this? I'd also need the content of
webilder.conf you have when this stack trace is given. Don't forget to omit
any sensitive information you may have in your webilder.conf before you
paste it here.

On Wed, Jun 22, 2011 at 5:45 AM, bhupi <
reply@reply.github.com>wrote:

> I installed the lastest release of webilder under ubuntu 11.04 using unity.
>  I did one reboot and webilder started automatically and ran fine.   Today I
> booted up and webilder didn't start.  I did the following at a terminal
> window:
> 
> /usr/bin/webilder_unity_indicator &
> [1] 3337
> laptop17:~$ Traceback (most recent call last):
>  File "/usr/bin/webilder_unity_indicator", line 9, in <module>
>    load_entry_point('Webilder==0.7.1', 'console_scripts',
> 'webilder_unity_indicator')()
>  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 305, in
> load_entry_point
>    return get_distribution(dist).load_entry_point(group, name)
>  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2244, in
> load_entry_point
>    return ep.load()
>  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1954, in
> load
>    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
>  File "/usr/lib/pymodules/python2.7/webilder/webilder_unity_indicator.py",
> line 14, in <module>
>    from webilder.base_applet import BaseApplet
>  File "/usr/lib/pymodules/python2.7/webilder/base_applet.py", line 11, in
> <module>
>    from webilder.config import config, set_wallpaper, reload_config
>  File "/usr/lib/pymodules/python2.7/webilder/config.py", line 126, in
> <module>
>    config = ConfigObject(DEFAULT_CONFIG_FILE)  # pylint: disable=C0103
>  File "/usr/lib/pymodules/python2.7/webilder/config.py", line 34, in
> **init**
>    raise ValueError, _("collection.dir is set to a non-directory, "
> ValueError: collection.dir is set to a non-directory, check your config
> file.
> 
> I found that if I edit my webilder.conf file, change the collection.dir
> field, all I did was I removed the quotes and saved the file,  then try to
> run webilder again it still fails.  I then put the collection.dir field back
> to how I originally had it and start webilder and it works.  So I am able to
> get it working but I have to manually do some tweaking.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thesamet/webilder/issues/21

## 

Sincerely yours,
Nadav

**Comment by thesamet** [comment]
Oops, please ignore the 'please file a new issue part' (I thought this comment was part of a previous issue), but I still need your webilder.conf

**Comment by bhupi** [comment]
Here is my webilder.conf

more webilder.conf
collection.dir = '/desktop/Webilder-Photos'
rotate.enabled = True
rotate.interval = 5
webshots.enabled = True
webshots.auto_download = True
webshots.username = 'myname'
webshots.password = 'mypass'
webshots.quality = 'wide'
webshots.cookie = 'My Cookie'
flickr.enabled = True
flickr.auto_download = True
flickr.rules = [{'album': 'Flickr', 'enabled': True, 'user_id': '', 'sort': 'Interestingness', 'tags': '1600x1200, wallpaper'}, {'album': 'Flickr', 'enabled': True, 'user_id': '', 'sort': 'Interest
ingness', 'tags': 'macros, nature'}, {'album': 'Flickr', 'enabled': True, 'user_id': '', 'sort': 'Interestingness', 'tags': 'hdr'}, {'album': 'Flickr', 'enabled': True, 'user_id': '', 'sort': 'Inte
restingness', 'tags': 'explore, exploretop20'}, {'album': 'Flickr', 'enabled': True, 'user_id': '', 'sort': 'Interestingness', 'tags': 'tag1, tag2'}, {'album': 'Flickr', 'enabled': True, 'user_id':
 '', 'sort': 'Interestingness', 'tags': 'date, travel'}, {'album': 'Flickr', 'enabled': True, 'user_id': '', 'sort': 'Interestingness', 'tags': '1920x1200, wallpaper'}, {'album': 'Flickr', 'enabled
': True, 'user_id': '', 'sort': 'Interestingness', 'tags': 'nature, scenery'}, {'album': 'Flickr', 'enabled': True, 'user_id': '', 'sort': 'Interestingness', 'tags': 'date, sunset'}, {'album': 'Fli
ckr', 'enabled': True, 'user_id': '', 'sort': 'Interestingness', 'tags': 'date, landscape'}, {'album': 'Flickr', 'enabled': True, 'user_id': '', 'sort': 'Interestingness', 'tags': 'date, sunrise'}]
flickr.download_interesting = True
flickr.scale_down = (1600, 1200)
autodownload.enabled = False
autodownload.interval = 24.0
autodownload.last_time = 1279772760.91654
webilder.layout = {'hpaned_position': 263, 'window_size': (1373, 810), 'window_position': (184, 37), 'info_expander': False}
webilder.wallpaper_set_method = 'gnome'
webilder.wallpaper_script = ''
webilder.wallpaper_compiz_screen_face = 'screen0,0'
webilder.installation_date = (2010, 7, 20)
webilder.stats = {'downloads': 3551, 'rotations': 45471}
filter.only_landscape = True

**Comment by thesamet** [comment]
Is '/desktop/Webilder-Photos' a valid path on your file system? i.e. in the shell, if you type 'ls -la /desktop/Webilder-Photos' does anything come up?

**Comment by bhupi** [comment]
That path is valid.  Let me try something.  I moved my .webilder directory out of the way and did a re-install of the software.  I then changed the collection dir to my path /desktop/Webilder-Photos in the default webilder.conf file.  I am going to reboot a couple of times and see if it runs.  Maybe I have something goofed up in my original webilder.conf file??

**Comment by bhupi** [comment]
I figured it out.  It has to do with my setup.   /desktop/Webilder-Photos is an nfs mount off another computer.  On bootup that mount is not initially present so webilder doesn't see it.  I am using automounter.   This problem wasn't there with the old verison of ubuntu so either I tweaked something in the old config or a new problem has crept in.    The /desktop/Webilder-Photos does mount after about 30 seconds on bootup.  I guess that is why it appeared that editing my webilder.conf file, changing something and then restarting fixed things.  It didn't have to do with the webilder.conf at all, after 30 seconds the mount appeared and then webilder could load my collection directory.   My tweaking webilder.conf and it seeming to fix things was a coincidence.   If you want I will close this bug.

**Comment by thesamet** [comment]
Your webilder.conf looks good. The exception you pasted comes up when Webilder checks whether the entry in collections.dir is a directory. You can try to recreate this by starting Python and typing in

> > > import os; os.path.isdir('/desktop/Webilder-Photos') 

If you get a False printed, then this is why the exception is raised. Could it be that /desktop/Webilder-Photos is a symlink and not a physical directory?

**Comment by thesamet** [comment]
Ok, thanks for clarifying the cause. One workaround  would be to put a webilder.conf at /desktop/Webilder-Photos on the root file system so webilder can see it if it starts before the nfs filesystem gets mounted. After the NFS share is mounted, the indicator will eventually reload the new config from there. It's a hack, but it might be good enough.
