### ISSUE TITLE
Feature request - Lubuntu

### ISSUE THREAD

**Issue by gir861** [thesamet/webilder#22]
Hi, I have used Your Webilder program from Ubuntu 9.04. But I have an old computer, so I was forced to use Lubuntu since 10.10, because Ubuntu works very slow... So I have a huge photo collection whitch I can't use. Please help me to use Your program again.

**Comment by thesamet** [comment]
I am not familiar with Lubuntu, but I'd be happy to help. I suggest you try to install from source as described in http://www.webilder.org/download.html.
