### ISSUE TITLE
Cannot install Webilder 0.7.1 on Debian or Linux Mint Debian Edition

### ISSUE THREAD

**Issue by Corin-EU** [thesamet/webilder#23]
Webilder has changed in going from 0.7 to 0.7.1 to require the Python module named appindicator.

This is even listed in the Debian controls file 

control:Depends: ${misc:Depends}, ${python:Depends}, python-gtk2, python-glade2, python-imaging, python-gnome2, libglib2.0-0, python-gnomedesktop, python-gnomeapplet, python-setuptools (>=0.6), python-appindicator

The only problem is that the package python-appindicator does not exist in Debian stable, testing or sid.

Package python-appindicator is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-appindicator' has no installation candidate

**Comment by thesamet** [comment]
There's currently no Debian package for webilder, only for Ubuntu. I'll see if I can get that fixed; in the meantime, you can install from source.

**Comment by Corin-EU** [comment]
Thanks for the fast response.

The thing I should have made clear is that I am trying to install from source.
- cd /usr/src/apps/Webilder-0.7.1
- python setup.py install --install-data=/usr/local/stow/Webilder-0.7.1/usr/local
  running install
  error: Could not find module No module named appindicator. Make sure all dependencies are installed.

**Comment by thesamet** [comment]
Thanks for letting me know. That would be an easy fix. In the mean time, if you look at setup.py, line 129 and remove the dependency on appindicatior it should work. The GNOME version of the applet does not depend on this module

**Comment by Corin-EU** [comment]
Having removed appindicator from line 129 of setup.py, Webilder 0.7.1 does install.

There is one further problem which I think is Debian specific.

The webilder egg info file   Webilder-0.7.1-py2.6.egg-info and webilder lib directory are installed in /usr/local/lib/python2.6/site-packages

From what I have found on the web, site packages is the appropriate "standard" name of the directory.

But when I come to run Webilder downloader, it fails with

Traceback (most recent call last):
  File "/usr/local/bin/webilder_downloader", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2672, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Webilder==0.7.1

Now if I move the egginfo file and webilder library from 

```
   /usr/local/lib/python2.6/site-packages
```

to 

```
  /usr/local/lib/python2.6/dist-packages
```

then all works as it should.

So for some reason on Debian, the info file and webilder lib directory need to be installed under dist-packages rather than site-packages.
