### ISSUE TITLE
Latest Ubuntu release 11.10 breaks Webilder

### ISSUE THREAD

**Issue by bhupi** [thesamet/webilder#26]
I upgraded to the lastest Ubuntu 11.10 (regretfully) and Webilder cannot load, says it is missing a dependency when I try to re-install.

**Comment by thesamet** [comment]
Thanks for letting me know. I'll take a look

**Comment by thesamet** [comment]
I've uploaded a new deb package that was generated with Ubuntu 11.10. It's version is 0.7.1-2. Can you try it out? Could you be more specific about the error you are seeing?

**Comment by bhupi** [comment]
After I did the upgrade I found that webilder was no longer installed.   I tried to install it via the deb package and I get this error:  Dependency is not satisfiable: python-gnomeapplet.   I will try your new build and let you know.

**Comment by bhupi** [comment]
I try to install webilder_0.7.1-2_all.deb via ubuntu software center and get the same error as before:

Dependency is not satisfiable: python-gnomeapplet

**Comment by thesamet** [comment]
Hi, I have eliminated this dependency, please try again with 0.7.1-3

**Comment by bhupi** [comment]
Yes the software does successfully install and run,,,BUT..  The idiots at Ubuntu, with all of the changes they have done, have broken a lot of things.  I have not been able to get any of the wallpaper changers that use to work to function probably.  They install but the background does not change.  I am seeing this problem with Webilder as well as with Wally and even with trying to use my own script to change the wallpapper.    The background only changes if you right click and select "Change Dekstop Background".  The background will change to any backgrounds that are available and I can even select my own backgrounds individually to display, but I can't get any background changer to work anymore.  

With Webilder I can see all of my backgrounds but when I select one to display it won't display.  I run gconf-editor and can see the backgrounds filenames changing as I select them under desktop -> gnome -> background.   So the backgrounds do get selected and look like they should display but they don't.  All I see is whatever the last background is that I selected under "Change Desktop Background".   I have several other bugs with this upgrade as well.  I really should of waited for a month or two before upgrading.    I am considering switching linux distros as I don't like Ubuntu anymore.

**Comment by bhupi** [comment]
I thought that maybe the background to display wasn't getting selected from desktop -> gnome -> background.  I thought maybe they changed the path to where the backgrounds were, but, I noticed that when I select one of the provided backgrounds that the desktop -> gnome -> background filename changes to the Ubuntu provided wallpaper and the wallpaper changes.   You would think that they are looking for the background from somewhere other than desktop -> gnome -> background since they want to get away from using gnome, but I haven't been able to find anything.

**Comment by bhupi** [comment]
I found that the wallpaper changer wallch works.   I went back and looked at webilder again and now I don't see the "desktop -> gnome -> background -> picture_filename" changing like it was before when I selected an image in Webilder and chose "set as wallpaper".  That makes no sense to me.

**Comment by vantt** [comment]
I am using Ubuntu 11.10 with default Unity. I successful setup webilder, notification icon is automatically displayed after restarting, but Webilder can not change the wallpaper background.

**Comment by thesamet** [comment]
Fixed in v0.7.2.

**Comment by bhupi** [comment]
I still have the problem, backgrounds won't change under both Unity and Gnome2.

**Comment by thesamet** [comment]
I should have mentioned that this is under a new setting. In the
Preferences window select the Advanced tab and choose Gnome3.
On Nov 13, 2011 7:10 AM, "bhupi" <
reply@reply.github.com>
wrote:

**Comment by bhupi** [comment]
Yes! It works now.  Thank You.
