### ISSUE TITLE
Feature request - Snapshot Scrapbook

### ISSUE THREAD

**Issue by ghost** [thesamet/webilder#27]
I really like the snapshot scrapbook function in JBS. Have a look. 

http://johnsadventures.com/archives/2007/11/a-snapshot-scrapbook-of-your-photos/ 

However JBS is just for Windows and I don't know any wallpaper changing program for Ubuntu which has this kind of function.

Thx
DuKane

**Comment by thesamet** [comment]
Hi DuKane, sounds like a cool idea, but unfortunately it is unlikely that I'll ever get to it. Patches are welcome! :)
