### ISSUE TITLE
Can't set a new wallpaper on KDE 4.4.2

### ISSUE THREAD

**Issue by BostonPeng** [thesamet/webilder#3]
After using Webilder on a GNOME-based system for quite some time I recently switched to running a KDE-based system. I was able to get Webilder running but I am unable to set a new wallpaper image, despite specifying that Webilder use KDE settings.

Here's my terminal output:

:~$ webilder_desktop 
/usr/lib/python2.6/dist-packages/webilder/config.py:140: DeprecationWarning: os.popen2 is deprecated.  Use the subprocess module.
  os.popen2(script)
ERROR: Couldn't attach to DCOP server!
:~$ 

In addition, calling up the Webilder settings also returns an error:

/usr/lib/python2.6/dist-packages/webilder/uitricks.py:23: GtkWarning: GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  gladefile), toplevel)

I'm running Webilder 0.6.3-1 (built from source) KDE 4.4.2 on top of Ubuntu 10.04.

**Comment by thesamet** [comment]
Closing since I have not received additional reports on this matter in the last 12 month. I'm assuming it's an isolated issue. Feel free to re-open if this still occurs.
