### ISSUE TITLE
Background image on left screen side 

### ISSUE THREAD

**Issue by enebre** [thesamet/webilder#35]
Hy, 
Is it possible to have the picture left of the screen,  instead of centered and extended, by editing the conf. file, somewhere on this ? ... And maybe an option for size
webilder.layout = {'info_expander': True, 'window_size': (700, 500), 'window_position': (1308, 379), 'hpaned_position': 180}
webilder.wallpaper_set_method = 'gnome3'
webilder.wallpaper_script = ''
webilder.wallpaper_compiz_screen_face = 'screen0,0'
webilder.installation_date = (2012, 4, 5)
webilder.stats = {'downloads': 69, 'rotations': 46}
filter.only_landscape = False

**Comment by thesamet** [comment]
I'm not sure I understand what you mean. Is it a bug or a feature request? Can you clarify.

**Comment by enebre** [comment]
Hy thank you for your answer, and sorry for my poor English.

Yes is a feature request, I didn't find a forum to place this request... so I did it here.

I would like to have the option to show the picture in original size on one side of the screen, upper left side for example, with a large screen I use the windows in small size on the other side of the screen.

**Comment by thesamet** [comment]
This could be accomplished using a custom script to set the wallpaper. Webilder can be configured to use a specific program to set a wallpaper (and %f is substituted in the command line with the full path of the image). That script could use ImageMagick or any other tool to transform the image and then set it as a wallpaper.
