### ISSUE TITLE
Webbilder doesn't work on Lubuntu 12.04

### ISSUE THREAD

**Issue by gazrac** [thesamet/webilder#37]
Hello, 

I installed it and it just doesn't work correclty, it's not able to set a wallpaper, I tried to configure "Set a wallpaper by running:" pcmanfm -set-wallpaper= but it doesn't work.

Can someone please tell me how to configure it?

Cheers!

garzaj

**Comment by thesamet** [comment]
Try adding %f, which is substituted for the full filename.  It looks like it should be

pcmanfm -set-wallpaper=%f   

Feel free to re-open this ticket if this does not resolve your issue.
