### ISSUE TITLE
Webilder in mate-ubuntu12.04

### ISSUE THREAD

**Issue by ahrambc** [thesamet/webilder#38]
My system is Ubuntu 12.04 with Mate

Webilder did not start in mate. It works fine with me in unity but not with mate.

What can i do

**Comment by thesamet** [comment]
Can you go on the command line and type

webilder_desktop (or WebilderDesktop) and report the output you get.

Best,
Nadav

On Wed, Aug 15, 2012 at 1:19 PM, ahrambc notifications@github.com wrote:

> My system is Ubuntu 12.04 with Mate
> 
> Webilder did not start in mate. It works fine with me in unity but not
> with mate.
> 
> What can i do
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thesamet/webilder/issues/38.

## 

-Nadav

**Comment by ahrambc** [comment]
When i goto the terminal and type " webilder_desktop " the webilder desktop screen is opened, but when i choose a photo to be as wallpaper, the following line is appears in the terminal

/bin/sh: 1: dcop: not found

**Comment by thesamet** [comment]
I am not familiar with Mate, but in the Preferences window you can try
different desktop settings (KDE/Gnome/etc). If nothing works, you'll have
to figure out a command line that can change the wallpaper on Mate. Then,
you can make webilder use that command (and use %f as a substitute for the
filename).

-Nadav

On Wed, Aug 15, 2012 at 3:41 PM, ahrambc notifications@github.com wrote:

> When i goto the terminal and type " webilder_desktop " the webilder
> desktop screen is opened, but when i choose a photo to be as wallpaper, the
> following line is appears in the terminal
> 
> /bin/sh: 1: dcop: not found
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thesamet/webilder/issues/38#issuecomment-7771806.

## 

-Nadav
