### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by tammerlane** [thesamet/webilder#5]
Is there a gui for Webilder? I looked all over and found nothing. Is there even a set of instructions? Thanx, tammerlane.

**Comment by tammerlane** [comment]
Is there a gui for Webilder? I looked all over and found nothing. Is there even a set of instructions? Thanx, tammerlane.

**Comment by thesamet** [comment]
Yes, there is a GUI. After installing webilder, you can start it by typing webilder_desktop in the command line.

Which installation method did you use?
