### ISSUE TITLE
python-pillow

### ISSUE THREAD

**Issue by fleamour** [thesamet/webilder#50]
The above is unsatisfiable dependency under elementary OS 0.2 Luna, itself based on 12.04 LTS.

**Comment by kristofwillen** [comment]
Same on Debian stable (unresolved deps with python-pillow and python-appindicator) : 

$ dpkg -i webilder_0.7.3-1_all.deb
Selecting previously unselected package webilder.
(Reading database ... 213901 files and directories currently installed.)
Unpacking webilder (from webilder_0.7.3-1_all.deb) ...
dpkg: dependency problems prevent configuration of webilder:
 webilder depends on python-pillow; however:
  Package python-pillow is not installed.
 webilder depends on python-appindicator; however:
  Package python-appindicator is not installed.
