### ISSUE TITLE
Webilder can't load PNG images

### ISSUE THREAD

**Issue by figure002** [thesamet/webilder#6]
Webilder can't load PNG images. This is strange, because a lot of wallpapers come in PNG format now. Also a big part of my wallpaper collection is in PNG format, so I miss out a lot of the good stuff when using Webilder.

I created a patch that fixes this issue. I couldn't find an upload option here, so let me know if you're interested. I'll mail it to you.

**Comment by thesamet** [comment]
Hi, thanks for implementing this feature and I'd like to merge your change in Webilder.

In order that I can easily review your code, please create a fork, apply your changes and send me a pull request. There are instructions on how to do this here http://help.github.com/forking/

Thanks,
Nadav

**Comment by figure002** [comment]
Ok Nadav, I think I did it. Just sent you a pull request.
